/**
 * Narrow, specific-term -> canonical-tag mappings used for tag suggestions.
 * These are intentionally more specific than category keywords (category =
 * broad bucket, tag = precise topic), matched against title + URL + folder.
 */
export const TAG_KEYWORD_MAP: Record<string, string> = {
  langchain: 'LangChain',
  langgraph: 'LangGraph',
  llamaindex: 'LlamaIndex',
  rag: 'RAG',
  llm: 'LLM',
  gpt: 'GPT',
  chatgpt: 'ChatGPT',
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  claude: 'Claude',
  gemini: 'Gemini',
  'vector database': 'Vector DB',
  embeddings: 'Embeddings',
  'fine-tuning': 'Fine-Tuning',
  'fine tuning': 'Fine-Tuning',
  'prompt engineering': 'Prompt Engineering',
  agent: 'Agents',
  python: 'Python',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  react: 'React',
  'next.js': 'Next.js',
  nextjs: 'Next.js',
  vue: 'Vue',
  svelte: 'Svelte',
  astro: 'Astro',
  tailwind: 'Tailwind CSS',
  docker: 'Docker',
  kubernetes: 'Kubernetes',
  aws: 'AWS',
  golang: 'Go',
  rust: 'Rust',
  sql: 'SQL',
  graphql: 'GraphQL',
  api: 'API',
  figma: 'Figma',
  'design system': 'Design Systems',
  typography: 'Typography',
  ux: 'UX',
  ui: 'UI',
  startup: 'Startups',
  'venture capital': 'VC',
  crypto: 'Crypto',
  bitcoin: 'Crypto',
  ethereum: 'Crypto',
  investing: 'Investing',
  resume: 'Resume',
  interview: 'Interviews',
  seo: 'SEO',
  marketing: 'Marketing',
  productivity: 'Productivity',
  'note-taking': 'Note-Taking',
  research: 'Research',
  paper: 'Papers',
  recipe: 'Recipes',
  fitness: 'Fitness',
  travel: 'Travel',
};

/** Content-type signals — surfaced as extra tags, not categories. */
export const CONTENT_TYPE_KEYWORD_MAP: Record<string, string> = {
  documentation: 'Documentation',
  docs: 'Documentation',
  readme: 'Documentation',
  tutorial: 'Tutorial',
  'how to': 'Tutorial',
  'how-to': 'Tutorial',
  guide: 'Guide',
  course: 'Course',
  video: 'Video',
  podcast: 'Podcast',
  changelog: 'Changelog',
  cheatsheet: 'Cheatsheet',
  'cheat sheet': 'Cheatsheet',
};
